### ISSUE TITLE
[Feature] Add function to check existence

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#101]
Provide a mechanism of detecting whether a file exists or not.

**Proposed Solution**
Add a builtin function, `$(gfileexists name)`, that returns a 1 if the file exists and 0 if the file does not exist.

This will allow constructs like:
```
ifeq ($(gfileexists depends),1)
  include depends
endif
```
**Alternatives Considered**
Standard mechanisms in GNU Make, including `$(wildcards)` do not work.

**Additional context**
This is from a customer request.

**Comment by rsbeckerca** [comment]
The above construct can be solved using:
```
-include depends
```

**Comment by Jojo-Schmitz** [comment]
Where the leading `-` means: don't bail out on error

**Comment by rsbeckerca** [comment]
> Where the leading `-` means: don't bail out on error

Exactly. So the include will not cause a missing depends file to abort the make.

**Comment by Jojo-Schmitz** [comment]
Does none of https://stackoverflow.com/questions/5553352/how-do-i-check-if-file-exists-in-makefile-so-i-can-delete-it help?

**Comment by rsbeckerca** [comment]
> Does none of https://stackoverflow.com/questions/5553352/how-do-i-check-if-file-exists-in-makefile-so-i-can-delete-it help?

I tried those solutions. Does not work regardless of the path involved `$..` or `/G..`. I think the `$wildcard` function may be broken. However, the use of shell calls to `test` will not work regardless in Guardian.

**Comment by rsbeckerca** [comment]
The workaround with `-include` is sufficient. See also #102
