### ISSUE TITLE
[Bug] The $(wildcards) built-in does not work in Guardian

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#102]
**Describe the bug**
`$(wildcards)` is not working at all for Guardian files.

**To Reproduce**
1. Create a Makefile 
2. Add anything referencing `$(wildcards)`
3. The reference will always return an empty string.

**Expected behavior**
`$(wildcards)` should work properly.

**NonStop**
 - OS: All
 - Version: 4.3g6

**Comment by rsbeckerca** [comment]
The file passed to `glob_in_dir` needs to be better handled. It currently is `./$vol.subvol.file`, which GMAKE thinks is a pattern, but it is not. In the NSK `stat()` function in `tandem_ext.c`, the leading `./` is now stripped so the `$(wildcard)` function does correctly process a single file, but not a Guardian pattern.

This is better than the prior situation but not sufficient. So the usage would be `$(wildcard $vol.subvol.file)` instead of an OSS pattern, because we drop to the NSK `stat()` that expects a Guardian name.

Still in progress.

**Comment by rsbeckerca** [comment]
More on this. Changing `glob()` in `glob.c` to detect `.` instead of `/` as a separator is not going to be easy. The code also has to detect the home directory, in Guardian. This part of the port was never done by NED.

**Comment by rsbeckerca** [comment]
I am trying to decide how to deal with this. The pattern for `$(wildcard $vol.subvol.file)` is being eventually passed to the `tandem_ext.c` `stat()` implementation. This calls `FILE_GETINFOLISTBYNAME_()`, which is fine for Guardian files and most usage. However, in the path through `wildcard`, the subvolume is being passed. This is a problem because `FILE_GETINFOLISTBYNAME_` returns 13 - obviously. One option is in `glob_in_dir` changing `$vol.subvol` into `/G/vol/subvol` and detect the leading `/` in `stat()` then call the actual NSK `stat` function, if that is even possible - it may require using `undef stat` to get at the underlying OSS call. I am worried about doing this and am looking for suggestions.

**Comment by rsbeckerca** [comment]
@Jojo-Schmitz @xidbhonaker Need some advice on the code. There is an implementation of `stat` in `tandem_ext.c`. I need to call the official `stat()` method, but it seems to have been made invisible because of the implementation. Any ideas on how to get to it?

**Comment by rsbeckerca** [comment]
> @Jojo-Schmitz @xidbhonaker Need some advice on the code. There is an implementation of `stat` in `tandem_ext.c`. I need to call the official `stat()` method, but it seems to have been made invisible because of the implementation. Any ideas on how to get to it?

(including @the4amfriend)

If this makes sense, I could detect something like `$data01.randall` as a sub-volume and synthesize a stat buffer for it with `st_mtime=0` and `st_mode=S_ISDIR`. It might work.

**Comment by xidbhonaker** [comment]
So tandem_ext.c is part of the code you inherited from HPE, right?  Maybe try commenting out references to the supplied stat() code and see if it builds... just a guess.

**Comment by rsbeckerca** [comment]
> So tandem_ext.c is part of the code you inherited from HPE, right? Maybe try commenting out references to the supplied stat() code and see if it builds... just a guess.

Not really. The official `stat()` requires a path starting with `/G` or `/E`. The `stat()` in `tandem_ext.c` expects a Guardian name form. The problem I'm having is that `$(wildcard)` is getting subvolumes, so the code in `stat()` gets error 13.

**Comment by xidbhonaker** [comment]
Easiest way to call CRE stat() would be to rename the tande_ext stat().   Otherwise you'd have to find stat() in the DLL and call it the hard way.

**Comment by rsbeckerca** [comment]
> Easiest way to call CRE stat() would be to rename the tande_ext stat(). Otherwise you'd have to find stat() in the DLL and call it the hard way.

I think faking the whole thing might be better. Have a look at the pushed commits cc42c34 and 12b9783.

**Comment by xidbhonaker** [comment]
Logged off for the weekend. I trust your judgment Sent from my Mobile. Spellings you may read are not as they appear.
-------- Original message --------From: "Randall S. Becker" ***@***.***> Date: 6/23/23  6:08 PM  (GMT-06:00) To: ituglib/gmake ***@***.***> Cc: xidbhonaker ***@***.***>, Mention ***@***.***> Subject: Re: [ituglib/gmake] [Bug] The $(wildcards) built-in does not work in
  Guardian (Issue #102) 

Easiest way to call CRE stat() would be to rename the tande_ext stat(). Otherwise you'd have to find stat() in the DLL and call it the hard way.

I think faking the whole thing might be better. Have a look at the pushed commits cc42c34 and 12b9783.

**Comment by Jojo-Schmitz** [comment]
> Easiest way to call CRE stat() would be to rename the tande_ext stat(). Otherwise you'd have to find stat() in the DLL and call it the hard way.

Yes, IMHO the only way(s)

**Comment by rsbeckerca** [comment]
I have the basics working, as long as the pattern is in the current directory and is a single level (base name), like `t*`. Processing patterns from a different directory is going to be difficult because make makes an assumption about '/' being the separator.

**Comment by rsbeckerca** [comment]
@Jojo-Schmitz The issue I am having is not being able to figure out how `glob_in_dir` decides what to pass to `opendir` at 

https://github.com/ituglib/gmake/blob/22e10d50b4b41bd7f5e62d5efc57cca86099a1da/glob/glob.c#L1297C1-L1300C1

It is possible that we may have to restrict wildcard to the current directory only.

**Comment by rsbeckerca** [comment]
> Sorry, don't have any clever idea for this

I'm working on "clever" now. :)
