### ISSUE TITLE
Create Website README for download/install of ituglib/gmake.

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#15]
The current default instruction do not apply to gmake. We should update them.

**Comment by rsbeckerca** [comment]
It might be appropriate to have the website point directly to the github README instead of a site-local copy. Although I can see that being an issue if github.com is blocked at some customers.

**Comment by rsbeckerca** [comment]
The website content should be in the GMake project content here so that it can be edited and approved as with any other component. Note that Jenkinsfile are here anyway, so changes to the content and process can be done in the fix for this.

**Comment by rsbeckerca** [comment]
Current steps captured from email are:

- Download the tar.gz file.
- Upload it to OSS
- Extract the gmakepak file from the archive”  tar -C/ -xzf 'zipped_package_file
- Put the gmakepak file into guardian: cp gmakepak /G/data/subvol – or whatever your home is
- Tell GUARDIAN that this is a PAK file: FUP ALTER gmakepak,CODE 1729
- Backup the existing GMAKE object: FUP RENAME gmake,gmakebak
- Restore the files: UNPAK gmakepak,*.*.*,listall,myid,map names ($data01.jenkins.*,$system.system.*)    - I think
- Secure the object so that anyone can run it: FUP SECURE gmake,"NUNU"

**Comment by rsbeckerca** [comment]
I have a draft `README` file available now. Please open the content using the ITUGLIB website and make suggestions. The content is in `/web/readme_files/gmake_install.html` on `\HPITUG`.

**Comment by Jojo-Schmitz** [comment]
Like https://ituglib.connect-community.org/apps/Ituglib/InstallHelp.xhtml?PackageKey=298&VersionKey=517 :-)
