### ISSUE TITLE
[Bug] Replace fopen() with stat() for file checking

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#25]
The current code uses `fopen(,"r")` to check whether a file exists or not. This should be changed to use stat or some more efficient mechanism to that does not modify the GUARDIAN access time of the file.

The code is located here:
https://github.com/ituglib/gmake/blob/ddece16e0155e6eb0b16b4d2202f986886c07eeb/dir.c#L759

**Comment by Jojo-Schmitz** [comment]
Is it possible in Guardian program to use stat()?

**Comment by rsbeckerca** [comment]
> 
> 
> Is it possible in Guardian program to use stat()?

`stat()` only works on files with OSS-style path names, so `/G/vol/subvol/file`. Conversion to that format would be required. The problem is that `stat()` is unaware of `getenv("DEFAULT")` or `getpwd()` values, so file qualification must be full instead of partial or unqualified as it would have appeared in the Makefile. This also has to take into account the `-C` argument that can override the run default subvolume.

**Comment by Jojo-Schmitz** [comment]
Why not using the POSIX's `access(name, F_OK)`? It should be far cheaper than `stat()` (which in turn is cheaper than `fopen()`, I guess, better for sure), as it does not grab all the detailed file infos we don't need here anyway?

**Comment by rsbeckerca** [comment]
> 
> 
> Why not using the POSIX's `access(name, F_OK)`? It should be far cheaper than `stat()` (which in turn is cheaper than `fopen()`, I guess), as it does not grab all the detailed file infos we don't need here anyway?
> 
> BTW, as per the man pages both `stat()` and `access()` are aware of the `=_DEFAULTS` define.

The documentation is somewhat confusing on J-series, as `access()` does not have a reference to GUARDIAN in the header, only OSS. Here are my findings:

- An unqualified file in the current directory works.
- A partially qualified file does not work: `No such file or directory`
- A fully qualified GUARDIAN file name does not work: `No such file or directory`
- An OSS-form path works if fully qualified, and the file is an edit file.
- An OSS-form path does not work if fully qualified, and the file is structured.

I think `stat()` behaves the same way. Perhaps we would be better using `FILE_GETINFO_`.

**Comment by Jojo-Schmitz** [comment]
Yes, for Guardian files in a Guardian program that should surly be the way to go.

**Comment by rsbeckerca** [comment]
> 
> 
> Yes, for Guardian files in a Guardian program using `FILE_GETINFO_` should surly be the way to go.

It should work for OSS files also, if referenced.

**Comment by Jojo-Schmitz** [comment]
Only there it doesn't feel right

**Comment by rsbeckerca** [comment]
`FILE_GETINFOBYNAME_` does not return a valid response to an OSS path. I'm wondering whether we could use both. If `FILE_GETINFO_BYNAME_` returns `13`, then try `access()`.
