### ISSUE TITLE
[Bug] DEFINES are not propagated to child processes by GMAKE.

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#31]
When `PROCESS_LAUNCH_` is called, it is set up with _potentially_ incorrect options. DEFINEs are not necessarily propagated by default. The question here is whether to force the use of:

`plist.name_options |= ZSYS_VAL_PCREATOPT_ALLDEFINES;`

or whether 

`plist.name_options = 0;` is sufficient to propagate.

**Comment by rsbeckerca** [comment]
GMAKE does not add any DEFINES into its context, so the question is one of pass-through only.

**Comment by xidbhonaker** [comment]
In recommendations to Nexbridge customers in the past, we've included that defines for an environment should be loaded prior to invoking GMAKE.  That allows for git to map defines to a given working area.  If those defines are not passed to the compilers then the issue breaks down.  I'd suggest that pass through should be enabled.

**Comment by rsbeckerca** [comment]
> 
> 
> In recommendations to Nexbridge customers in the past, we've included that defines for an environment should be loaded prior to invoking GMAKE. That allows for git to map defines to a given working area. If those defines are not passed to the compilers then the issue breaks down. I'd suggest that pass through should be enabled.

Me too. My question is, what is the real default behaviour? At one point (ok, it was D-series), `DEFMODE ON` was the default but that may have only been in TACL. Do we have to change code? It's a one-liner no matter what.

**Comment by xidbhonaker** [comment]
That was in TACL.  I seem to recall (without doing an RTFM) that with options of zero, no defines are propagated (there is not a ‘default’ and there is only a one bit flag in the options parameter.

**Comment by rsbeckerca** [comment]
> 
> That was in TACL. I seem to recall (without doing an RTFM) that with options of zero, no defines are propagated (there is not a ‘default’ and there is only a one bit flag in the options parameter.

OK, I'll turn it on, as above.
