### ISSUE TITLE
[Bug] Completion Codes ignored by GMAKE

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#38]
When a compiler returns a warning, CC=1, GMAKE ignores the result. This was deliberately put in by HPE DEV for some reason.

The difficulty with using Make syntax:
```
        -$(TAL)/in .../
```
is that any error is ignored. This is something to consider. There is no solution in GNU Make either but the behaviour is different than in GNU Make, which would fail the rule in the case of a compiler warning.

**Comment by rsbeckerca** [comment]
What I'm planning in the GMAKEN fork is to add a `-Wlegacy-cc` option or `--fail-on-cc1` (or something like that) to keep `CC=1` as a non-failure if desired. Having done some research, the GUARDIAN compilers `CCOMP`, `C`, `TAL`, `NMC`, do report `CC=1` in the case of warnings, while the OSS compilers do not. So the compilers themselves have a disparity between the two personalities. However, utility failures, like `diff` and `cmp` reporting a `CC=1` will be ignored by GMAKE as it currently stands. This is not desirable, so we need some way of dealing with this.

Perhaps we need something more like the `-` operator on command lines but that would ignore any CC. Perhaps `+` (or some other unique character, like `!`, to specifically ignore `CC=1` might be a better approach.

**Comment by rsbeckerca** [comment]
I have run through a test of `DDL`, `SCOBOLX`, `TAL`, `C`, `CCOMP`, `NMC`, and `COBOL85`, testing completion codes with `?NOWARN`/`#pragma NOWARN`. It appears that the old defect of suppressed warnings still resulting in `CC=1` no longer exists in those processors.

I'm going to work something out in the GMAKEN fork, probably `-Wlegacy-cc` to reenable suppression of `CC=1`, but I consider this "feature" in GMAKE that we inherited to be a defect, but we have to preserve compatibility for a customer who might depend on it. Thoughts?

**Comment by rsbeckerca** [comment]
I feel silly about this. The CC issue is only in the test driver for the internal launch, not in the main processing. This is not an issue.

**Comment by rsbeckerca** [comment]
I have been able to reproduce this issue using DDL. It requires a very specific condition regarding a `REDEFINES` clause introducing a level in the C structure. Suppressing this warning still causes DDL to report a `CC=1`. We need a solution for this. Options:

1. Make a special case for DDL so that CC=1 is not considered a failure.
2. Provide a `+` character, like the leading, `-`, to suppress the warning.
3. Extend `-` to have a set of completion codes, like `-{1}`.

**Comment by rsbeckerca** [comment]
> 
> 
> I have been able to reproduce this issue using DDL. It requires a very specific condition regarding a `REDEFINES` clause introducing a level in the C structure. Suppressing this warning still causes DDL to report a `CC=1`. We need a solution for this. Options:
> 
>     1. Make a special case for DDL so that `CC=1` is not considered a failure.
> 
>     2. Provide a `+` character, like the leading, `-`, to suppress the warning.
> 
>     3. Extend `-` to have a set of completion codes, like `-{1}`.

Instead of 2 and 3, go with 1 for `$SYSTEM.SYSTEM.DDL` and then support `PARAM LEGACY_WARNING 1` to force the old behaviour in all cases. I'm going to try this in the GMAKEN fork and see how users respond to it.

**Comment by rsbeckerca** [comment]
The feedback so far is not to fix this because NonStop compilers report CC=1 for warnings while other platforms do not consider warnings as CC worthy, so report CC=0.

**Comment by rsbeckerca** [comment]
I had another vote to change the behaviour so that CC=1 is only suppressed for `$SYSTEM.SYSTEM.DDL`, and support legacy behaviour (existing), using `PARAM LEGACY-CC 1` or command option `--legacy-cc`.

**Comment by rsbeckerca** [comment]
Sadly, the code to avoid CC=1 warnings, as delivered in GMAKE was not correct in the first place. I am trying to resolve this and if I can fix it, will post the changes.

**Comment by rsbeckerca** [comment]
I have a fix for this issue and the correct error/warning report.

**Comment by xidbhonaker** [comment]
I've read through this.  Glad you've polled your users and the one(s) that cared like your 'ignore except for DLL but allow override' option.  That seems very reasonable to me.

**Comment by rsbeckerca** [comment]
This is the manual entry I have written for it:

### Error Handling

The `GMAKE` program differs from the standard GNU Make in terms of how
completion codes are handled. Because of differences in completion codes
generated by compilers, handling has deviated. The original GMAKE port always
considered completion code 1 as an ignored warning. This has not always been
a desirable outcome. In the case of the DDL compiler, there is no way to
suppress `CC=1` even if warnings are ignored. As a result, `GMAKE`
considers `CC=1` generated by DDL to be ignored in all cases. Other
processes generating `CC=1` are treated consistently with GNU Make and will
cause the recipe to fail. The `--legacy-cc` option, or `PARAM LEGACY-CC 1`
will cause the original GMAKE port behavior to be used, where `CC=1` will
always be considered an ignored warning.
