### ISSUE TITLE
[Feature] Add =SEARCH DEFINE support

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#45]
Add SEARCH define support. This is somewhat complex as there are absolute and relative values. This is needed for ELD/XLD support:

```$(define_add =srch,search[,subvol=x]...[,relsubvol=y])```

`subvol` and `relsubvol` attributes can be in any order. The items are not indexed. That will be handled by the define processor itself.

**Comment by Jojo-Schmitz** [comment]
Why define_Add rather than add_define like in OSS?

**Comment by rsbeckerca** [comment]
> 
> 
> Why define_add rather than add_define like in OSS?

Well, I was going for something more familiar to TACL programmers (#DEFINEADD). And, well, it's already done in the GMAKEN fork.  ;)

**Comment by Jojo-Schmitz** [comment]
`$(add_define ...)` has the extra benefit to look the same on Guardian and OSS, and so give more portability of makefiles

**Comment by rsbeckerca** [comment]
It's one line to do both. I could live with that.

**Comment by rsbeckerca** [comment]
Here is what the code looks like:

```
  FT_ENTRY ("define_add",    3,  3,  1,  func_define_add),
  FT_ENTRY ("add_define",    3,  3,  1,  func_define_add),
  FT_ENTRY ("define_delete", 1,  1,  1,  func_define_delete),
  FT_ENTRY ("delete_define", 1,  1,  1,  func_define_delete),
```

**Comment by Jojo-Schmitz** [comment]
It is `del_define` in OSS

**Comment by Jojo-Schmitz** [comment]
(and `alter_define`, in case you want to add that too)

**Comment by Jojo-Schmitz** [comment]
And `info_define`, `reset_define`, `set_define`, `show_define`

**Comment by rsbeckerca** [comment]
I have no intention of implementing the full set of define operations. Just what is necessary to do builds.

**Comment by Jojo-Schmitz** [comment]
I just wanted to mention them for completeness ;-)
