### ISSUE TITLE
[Bug] OSH does not start when run by GMAKE

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#50]
When `OSH` is used within GMAKE, it does not run correctly.

1. Create a `Makefile` that runs `OSH`
2. The recipe should be something like
```
all:
        $SYSTEM.SYSTEM.OSH -c "mxcmp bob"
```

`OSH` will not run. This results from the `IN` file being incompatible with what `OSH` or something further down in OSS does not like.

If the `IN` file is set to something friendly, like an EDIT file, `OSH` appears to correctly start the process. It might be useful to either detect this situation and set `IN` to something useful automatically, or have a temporary file variable that can be used, like `$(temp)`, like `$SYSTEM.SYSTEM.OSH /IN $(temp)/ -c "mxcmp bob"`

**Comment by Jojo-Schmitz** [comment]
Maybe using `-osstty`?

**Comment by rsbeckerca** [comment]
> 
> 
> Maybe using `-osstty`?

Yes this works. Thanks. I guess we just need to document it.

**Comment by Jojo-Schmitz** [comment]
I'd rather force that -osstty whenever a $(SH) is used

**Comment by rsbeckerca** [comment]
> I'd rather force that -osstty whenever a $(SH) is used

It's an interesting thought but causes issues when someone wants to do an "obey" think, like `$(SH)/IN script/`, which also works. It does bring up the possibility of the following:

```
OSHARG=-osstty
SH=$SYSTEM.SYSTEM.OSH $(OSHARG)
```
So someone could turn off the default behaviour if they want to. I would be fine with that.

**Comment by rsbeckerca** [comment]
Pushed a new version for review.
