### ISSUE TITLE
[Feature] Conversion function from GUARDIAN to OSS

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#52]
I have an urgent request to provide a mechanism to convert a GUARDIAN name to an OSS name. The basic concept is: `$(pname file)` which returns the OSS name of a file. If the file is an EXPAND name, the `/E` qualifier will be added. Otherwise the name will be `/G` relative.

### Usage Example

```
SRC=$data01.randall.myfile
OSSSRC:=$(pname $(SRC))

OBJ: $(SRC)
        $(SH) -c "something $(OSSSRC)"
```

I need to turn this around pretty fast.

**Comment by Jojo-Schmitz** [comment]
Maybe better "pname -s"

**Comment by rsbeckerca** [comment]
> 
> 
> Probably better "pname -s"

I don't see any value in not having `-s` implicitly. This will not actually run `pname`, but do what `pname` does. Without `-s`, you get `pname: $a.b.c --> /G/a/b/c`, which is not useful in a script. I think a result of `$(pname $a.b.c)` -> `/G/a/b/c` is sufficient.

**Comment by Jojo-Schmitz** [comment]
Yes. We just want the oss name,  nothing else,  just like "pname -s" does.
But why not using it directly?

**Comment by rsbeckerca** [comment]
> 
> 
> Yes. We just want the oss name, nothing else, just like "pname -s" does.
> But why not using it directly?

Because it is a whole lot easier to take the results of FILENAME_RESOLVE_ and convert it to an OSS name, rather than trying to use `PROCESS_LAUNCH_` and `PROCESS_SPAWN_` to run `OSSTTY`, `OSH`, and `pname`. I tried running this from the `$(shell)` function previously implemented and it is just too complex an orchestration of processes when to actually convert the GUARDIAN name is really about 10 lines of code and does not involve all of the process creates.
