### ISSUE TITLE
Add PARAM and ASSIGN capability

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#63]
The current GMAKE program passes it's received PARAM and ASSIGN messages to its children. This is insufficient for complex makefiles. Add a mechanism to clear and add PARAM and ASSIGN values as part of recipes.

**Comment by rsbeckerca** [comment]
This will be prototyped in the GMAKEN fork.

**Comment by rsbeckerca** [comment]
Proposed functions to do this:

### Params

`$(param name value)` to add a param
`$(clear_param name)` to remove a param. If name is `*`, then all params are cleared.

This is the closest to TACL function. Possibly `$(add_param)` instead?

### Assigns

`$(assign name file|subvol|volume,[optional args])`. Possibly `$(add_assign)` instead?

`$(clear_assign name)` to remove an assign. If name is `*`, then all assigns are cleared.

Thoughts?

**Comment by Jojo-Schmitz** [comment]
What's the Guadian comman, `assign` or `add assign`? Follow that in the make syntax.

**Comment by rsbeckerca** [comment]
> 
> 
> What's the Guadian comman, `assign` or `add assign`? Follow that in the make syntax.

It's `assign bob,$a.b.c` to add and `clear assign bob` to remove. I don't like reusing "clear" for both - it makes it annoying to implement.

**Comment by Jojo-Schmitz** [comment]
`clear_assign` and `clear_param` is find, just adding an underscore to the TACL syntax. Drop the `add_` though.

**Comment by rsbeckerca** [comment]
Works for me

**Comment by rsbeckerca** [comment]
Using functions in recipes has an unfortunate drawback. When a recipe is executed, like:
```
obj1: src1
        $(param SWAPVOL $OSS)
        $(TAL) /in $</ $@
        $(clear_param SWAPVOL)
```
The functions are evaluated prior to executing the $(TAL) statement, so there are actually no PARAMs. Rewriting the recipe as follows works:
```
obj1: src1
        $(clear_param *)
        $(param SWAPVOL $OSS)
        $(TAL) /in $</ $@
```
The above works in my implementation, but it might be more useful for some customers to have something like:
```
obj1: src1
        param SWAPVOL $OSS
        $(TAL) /in $</ $@
        clear param all
```
and have the `param` and `clear` operations parsed inside `launch_proc()` as if they are programs themselves.
