### ISSUE TITLE
[Feature] Support OS-specific Variables

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#74]
Being able to create a `makefile` that supports multiple platforms is highly desirable. The following definitions are proposed. Please comment on others:

Platform variable:
`TNS_PLATFORM=E|X` (maybe `V` also)?

OS level variable:
`TOS_VERSION=L21|J06`

These should be usable with the following construct, and can appear in recipes.
```
ifeq($(TNS_PLATFORM),E)
   do something for TNS/E
else ifeq($(TNS_PLATFORM),X)
   do something for TNS/X
endif
```

**Comment by rsbeckerca** [comment]
Something else that can be done here, is removing the `NMC` variable, which has no meaning on L-series.

**Comment by xidbhonaker** [comment]
The E/X only makes sense.  It's conceivable that in future a makefile might need to know if it's virtual or converged, but a) I can't think of a use case for that at this time, and b) I haven't researched whether it's something you can ascertain from APIs.

All looks good.

**Comment by rsbeckerca** [comment]
> 
> 
> The E/X only makes sense. It's conceivable that in future a makefile might need to know if it's virtual or converged, but a) I can't think of a use case for that at this time, and b) I haven't researched whether it's something you can ascertain from APIs.
> 
> All looks good.
> 
> As for getting to review my use cases, it will be later today before I can find cycles for that, but I can't think of any off the top of my head.

I think I can wait for your use cases, or we can open a new issue with them. Your call.
