### ISSUE TITLE
[Feature] Add finer resolution and comparisons to TOS Version

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#76]
Bill has requested increasing resolution of TOS Version in default variables. I think this should be handled by a separate variable because there is significant value just working with the Major release numbers (e.g., `L20`, `L21`). This would be something like `TOS_VERSION_FULL` containing `L20.10`. The question of usage is more extensive since there is no `>` or `<` operator for ifeq in GNU Make.

The normal GNU Make solution is to use `ifeq ($(shell expr ...),0)`, which may be possible with suitable TACL macros replacing `expr ...`.

One alternative is to implement `ifgt` and `iflt` for string comparisons.

Another alternative is to implement `ifeq ($(tosallowed $(TOS_VERSION_FULL),>L18.01,<=L20.10,...)),0)` where a new function like `tosallowed` would take the version to check, then a series of `=`,`!=`,`<`,`<=`,`>`,`>=` and versions. Implementing this would not be too onerous as a new function.

**Comment by rsbeckerca** [comment]
There is an enhancement on the books for GNU Make referring to `$(compare n m)`, which returns a zero/non-zero result. It has not yet been merged. I think something more along the lines of a more general `$(vcompare x y) -> -1,0,1` would suit our purpose better. The basic concept is an ECLIPSE-like version compare, with the following examples:

- `$(vcompare 1.6.100 1.6.1)` returns `1` for greater than.
- `$(vcompare 1.6.100 1.6.100.5)` returns `-1` for less than.
- `$(vcompare 1.6.C 1.6.A)` returns `1` for greater than.
- `$(vcompare ADR AEF)` returns `1` for greater than.
- `$(vcompare J06.22.0 J06.23.0)` returns `-1` for greater than.

**Comment by rsbeckerca** [comment]
@xidbhonaker My thought on `$(vcompare J06.22.01 J06.22.1)` is that the comparison is ambiguous rather than equal. Our choices are:

1. We could report either `-1`, because `01` sequences less than `1` textually, or
2. `2` meaning equivalent but different values.
3. `0` meaning equivalent.

I think that option 1 is probably the way to go. The values are not strictly equal or even truly equivalent in my view. The value of `$(TOS_VERSION_FULL)` will never report `J06.23.1`, so encoding that in a `Makefile` would be a bug in the `Makefile`. This makes the code a bit more complex. The rough algorithm would work as follows:

1. Split the two version text into segments by `.` and ` ` separators.
2. For each segment index, if the segment contains non-numeric values in either version, do a simple case-insensitive text compare.
3. For each segment index, if the segment is entirely numeric, convert to decimal and numerically compare. If the text lengths of the numbers are different, report the shorter string as greater (so `01` is less than `1`).

To compare TOS versions, like `J06.23.01`, the first segment is a text compare, and the second and third are numeric.

To compare SPR versions, like `T1200L01 ACF`, both segments are text compares. Note: we do not have a mechanism of finding the SPR of anything, although that might lead to a `$(vproc file)` function at some point. If we do that, the `$(vcompare)` should support comma separators between version strings, because the `$(vproc file)` will give us something ambiguous upon expansion.

**Comment by rsbeckerca** [comment]
The current `uname()` call only reports `J06.22` at present. Is this sufficient?

**Comment by Jojo-Schmitz** [comment]
`gtacl -p sutver`

**Comment by rsbeckerca** [comment]
> 
> 
> `gtacl -p sutver`

No API?

**Comment by Jojo-Schmitz** [comment]
None that I'd know

**Comment by rsbeckerca** [comment]
For `vcompare` it is easier to use a comma separator, so I'm going with that.

**Comment by xidbhonaker** [comment]
You could check out the Guardian call to SUTVER_GET_().

**Comment by rsbeckerca** [comment]
> 
> 
> You could check out the Guardian call to SUTVER_GET_().

Thanks. `ReleaseId` is the string to use from that proc.

**Comment by xidbhonaker** [comment]
I thought it might be but the examples in the documentation were sorely lacking.

**Comment by rsbeckerca** [comment]
> 
> 
> I thought it might be but the examples in the documentation were sorely lacking.

And not available for Cross-Compilers.

**Comment by rsbeckerca** [comment]
Pull request created. There is an issue building, so we need to build on a real NonStop server. Otherwise, we would have to publish an HPE file.

**Comment by xidbhonaker** [comment]
The header file you need, psvgth.h, isn't on the cross compilers  disk.  However, it's not on at least one of the machines I looked at (other files are in the subvolume, but not PSVGTH or PSVGT).  

I copied the version from HPITUG (J-series) to my PC, build an L object, pushed it to the server and it ran just fine.

Realizing that it could in theory break in the future, but I doubt it.

**Comment by xidbhonaker** [comment]
The header file you need, psvgth.h, isn't on the cross compilers  disk.  However, it's not on at least one of the machines I looked at (other files are in the subvolume, but not PSVGTH or PSVGT).  

I copied the version from HPITUG (J-series) to my PC, build an L object, pushed it to the server and it ran just fine.

Realizing that it could in theory break in the future, but I doubt it.

**Comment by rsbeckerca** [comment]
> 
> 
> The header file you need, psvgth.h, isn't on the cross compilers disk. However, it's not on at least one of the machines I looked at (other files are in the subvolume, but not PSVGTH or PSVGT).
> 
> I copied the version from HPITUG (J-series) to my PC, build an L object, pushed it to the server and it ran just fine.
> 
> Realizing that it could in theory break in the future, but I doubt it.
> 
> Wonder if we could ask permission? Or instruct users to get the file from their NonStop before building gmake?

I put instructions in MANUAL.md about this. We cannot push this to an Open Source project without consequences.
https://github.com/ituglib/gmake/blob/fix-76/MANUAL.md#workstations

**Comment by xidbhonaker** [comment]
That makes sense.  I’m sure we could get all the permissions we wanted… and even add appropriate disclaimers.  I think the permission would be complete by at least 2024.  :-)

I was focused on you building an executable, not the customer building it.  Old thinking. Sorry.

Building on a cross compiler or a NonStop will work.
