### ISSUE TITLE
Remove old VPROC entry

### ISSUE THREAD

**Issue by rsbeckerca** [ituglib/gmake#8]
The current VPROC shows the old VPROC entry (`19SEP14`). This should be removed. The T-number needs to be changed/handled. The SPR should be changed to something more useful, and `4_1` should be `4_1g`.

```
VPROC - T9617H01 - (03 MAY 2016) SYSTEM \HPITUG   Date 04 OCT 2020, 13:28:00
Copyright 1986-2016 Hewlett Packard Enterprise Development LP

$SYSTEM.SYSTEM.GMAKE2
     Binder timestamp:  04OCT2020 13:24:23 LCT, 04OCT2020 18:24:23 GMT
    Version procedure:  T0593H01_01FEB15_GMAKE_19SEP14
    Version procedure:  T0593H01_30SEP20_GMAKE_30SEP20_AAD_4_1
    Version procedure:  T8432H04_22MAY2018_CCPLMAIN_23OCT2017_ACH
    TNS/E Native Mode:  runnable file
```

**Comment by rsbeckerca** [comment]
What I am proposing is to use git tags to control the contents of a VPROC. The VPROC calculation has two dates. The first is a question mark. The second can be the build date, constructed using the `date` utility. The SPR and GMake version can be established using tags, as in the following options:

### Option 1
```
git tag -a 4.1g_AAE
```
which would translate into the AAE SPR based off GMake 4.1 for GUARDIAN. `git describe` can be used to pull the latest tag.

### Option 2

Alternatively, we could compute the SPR based on number of commits, since there will not be a large number, beyond the tag. So assuming:
```
git tag -a 4.1g
```
And with `HEAD` being `5` commits more recent than the tag, `git describe` would report `4.1g-5`. The `5` could be translated to `AAE`. I am not so happy with this solution, however.

**Comment by Jojo-Schmitz** [comment]
Drop the `T0593H01_01FEB15_GMAKE_19SEP14`.
Change the `T0593H01_30SEP20_GMAKE_30SEP20_AAD_4_1` to e.g. `T0593**V**01_30SEP20_GMAKE_30SEP20_4_1g`

**Comment by rsbeckerca** [comment]
Candidate version.sh script that will load a `#define` as part of the build:

```
PRODUCT_NUMBER=T0593V01
PRODUCT_NAME=GMAKE
COMMITTER_DATE=`date --date="@\`git show -s --format=%ct HEAD\`" +%d%b%g | tr '[
:lower:]' '[:upper:]'`
VERSION_STRING=`git describe --tags --long | sed 's/-.*-/_/' | sed 's/\./_/g'`

echo ${PRODUCT_NUMBER}_${COMMITTER_DATE}_${PRODUCT_NAME}_${VERSION_STRING}
```
results in `T0593V01_04OCT20_GMAKE_4_1g_g313c492` when run at any time. I could differentiate `V01` to `H01` and `L01` using `uname`, but I'm fine with V01. This look good to integrate?

**Comment by Jojo-Schmitz** [comment]
It does to me
